# Name of workflow
name: Lint Workflow

# Trigger workflow on pull requests to specific branches
on:
  pull_request:
    branches:
      - develop
      - staging

# Jobs to run
jobs:
  lint:
    # Specify the OS to run the job
    runs-on: ubuntu-latest

    # Steps to perform
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run linting
      - name: Run lint
        run: npm run lint
